### PR TITLE
Change 'polymer#1 - 2' to 'polymer#1.9 - 2'

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@abdonrd PTAL.

**Comment by abdonrd** [comment]
I prefer follow the same pattern as the `PolymerElements`.

**Comment by FluorescentHallucinogen** [comment]
@abdonrd Sorry, but @PolymerElements use `polymer#1.9 - 2`, not `polymer#1 - 2`:

https://github.com/PolymerElements/paper-input/blob/master/bower.json#L31
https://github.com/PolymerElements/app-route/blob/master/bower.json#L19
https://github.com/PolymerElements/iron-location/blob/master/bower.json#L26

If we use `^1.9.0` in [line 37](https://github.com/abdonrd/device-orientation/blob/master/bower.json#L37), we should use the same version as minimum in [line 26](https://github.com/abdonrd/device-orientation/blob/master/bower.json#L26), i.e. `1.9 - 2`.

**Comment by abdonrd** [comment]
Ouch! You are right. I don't know why I thought they used `polymer#1 - 2`. 🤔

**Review by abdonrd — APPROVED** [review]

**Pull request merged**
