### PR TITLE
Add more keywords

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
* Add `polymer-element`, `polymer-2` and `polymer-2-hybrid` keywords to `bower.json` file to indicate that this is Polymer 1.x/2.x hybrid element.
* Add `api` keywords to `bower.json` file because `<device-orientation>` web component is a part of my [progressive-elements](https://www.webcomponents.org/collection/FluorescentHallucinogen/progressive-elements) collection that is a set of web components for [modern web APIs](https://whatwebcando.today) such as Payment Request API, Media Session API, etc. People can find these web components by the `api` keyword.

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@abdonrd PTAL.

**Comment by abdonrd** [comment]
Thanks!

**Comment by FluorescentHallucinogen** [comment]
@abdonrd Could you please release the new version `2.0.3` for these changes to take effect on https://webcomponents.org?

**Comment by abdonrd** [comment]
Done!

**Pull request merged**
